#lang racket
(require parser-tools/lex)

(provide (all-defined-out))

(define-tokens value-tokens (IDENTIFIER
                             NUMBER
                             DATA-TYPE
                             ACCESS-SPECIFIER
                             LITERAL
                             INTEGER
                             FLOAT
                             STRING
                             CHAR
                             HEADER
                             THIS-IDENTIFIER
                             FUNCTION-OBJECT-CALL
                             BOOLEAN
                             TEXT
                             IDENTIFIER-CAPITALIZED
                             GETTER-NAME
                             SETTER-NAME
                             ))
(define-empty-tokens op-tokens (ASSIGN
                                TERMINATOR
                                PLUS
                                PLUS-ASSIGN
                                MINUS
                                MINUS-ASSIGN
                                MUL
                                MUL-ASSIGN
                                DIV
                                DIV-ASSIGN
                                MOD-ASSIGN
                                COLON
                                CIN
                                COUT
                                COMMA
                                SHIFT-R
                                SHIFT-L
                                LPAREN
                                RPAREN
                                RETURN
                                OR
                                AND
                                NOT
                                BREAK
                                DEFAULT
                                BRACE-OPEN
                                BRACE-CLOSE
                                ELSE
                                IF
                                SCOPE-RESOLUTION
                                HASH
                                INCLUDE
                                QUOTE
                                USING
                                DOT
                                H
                                HH
                                HPP
                                INCREMENTER
                                DECREMENTER
                                FOR
                                MORE
                                LESS
                                MORE-EQUAL
                                LESS-EQUAL
                                WHILE
                                TILDE
                                CLASS
                                STRUCT
                                DEFINE
                                IOSTREAM
                                VECTOR
                                CMATH
                                CSTDLIB
                                CSTDIO
                                CSTRING
                                CTIME
                                ALGORITHM
                                ANGLE-BRACE-OPEN
                                ANGLE-BRACE-CLOSE
                                IFDEF
                                IFNDEF
                                ELIF
                                ENDIF
                                UNDEF
                                ERROR
                                WARNING
                                PRAGMA
                                LINE
                                MAIN
                                GET
                                VOID
                                TEMPLATE
                                TYPENAME
                                NAMESPACE
                                EQUAL
                                NOT-EQUAL
                                STRING-NAME
                                RESIDUAL
                                EOF))
